### ISSUE TITLE
Re-license 

### ISSUE THREAD

**Issue by suprafun** [CZDanol/AnotherCraft#1]
Hello, sorry to bother you, but would it be possible to please re-license this project under a different license ? I have difficulty understanding the CC-BY-4.0 license. I think its similar to MIT or BSD, but I am unsure. In my case I would like to learn from this project towards writing my own voxel engine. Thank-you.

**Comment by CZDanol** [comment]
Heyo,
err whatever, you can use any code, learn from it any way you want, you can use it for commercial stuff, just put my name in the credits.

**Comment by suprafun** [comment]
Thank-you so very much.

**Comment by CZDanol** [comment]
Just please note that my code is not friendly towards beginners (don't know on what level you are).
