### ISSUE TITLE
Thesis source if possible.

### ISSUE THREAD

**Issue by PsychicBlade** [CZDanol/AnotherCraft#2]
Please provide a editable version of the thesis so if any contributor wants to translate to English.
The original MS Docx or Tex files will be more helpful than the pdf, because pdf is only concerned with the preserving the visual design at print, so the text is all obfuscated when copied to translate.

**Comment by CZDanol** [comment]
Allright. I have added the master thesis sources. I've also added a partial translation to EN with sources (I started translating but then I lost the drive).

**Comment by PsychicBlade** [comment]
Oh, thanks a lot, I will check them out in a bit.

**Comment by PsychicBlade** [comment]
- I do not speak CZ, I will use translate with google translate, and will correct the technical stuff if I notice any, you can do a semantic check later.
- I don't have LaTex on my current computer (and not the complete knowledge to use it either), so I will use markdown, hopefully you can use that.

I hope this will help.

**Comment by CZDanol** [comment]
Sure, if you do the coarse translation, I can then read it through and do eventual corrections :)  Much less work for me. Feel free to reach to me on discord for questions (Danol#2663)
